### ISSUE TITLE
EDITOR considered as empty if there is a space in the variable

### ISSUE THREAD

**Issue by ColinHebert** [TomPoulton/hiera-eyaml#127]
My editor is current `subl -w` (option for the editor to wait and not send an exit status right away)

A call to `eyaml edit` results in the following:

> [hiera-eyaml-core] Editor not found. Please set your EDITOR env variable

**Comment by elyscape** [comment]
@ColinHebert Can you confirm whether this has been fixed?

**Comment by ColinHebert** [comment]
I can confirm that it works. Awesome!
