### ISSUE TITLE
Hiera can't decrypt eyaml values

### ISSUE THREAD

**Issue by jas02** [TomPoulton/hiera-eyaml#133]
Hi, I did successfully install on test server hiera-eyaml. I am able encrypt password with eyaml and retrieve this value using hiera command (hiera -c /etc/puppet/hiera.yaml snmp::ro_community fqdn=server.name).

Unfortunately on production server, with same settings and same versions I am not able get decrypted values and receiving just encrypted password (ENC[PKCS7,MIIBeQYJK...]) with hiera command.

Hiera version is 1.3.4, hiera-eyaml 2.0.6 and Puppet 3.7.3. 

Any idea what am I doing wrong? How can I debug it, fix it? Any help would be great.

Regards

Lumir

**Comment by TomPoulton** [comment]
Hi @jas02, can you post your hiera.yaml file, it looks like the eyaml backend isn't being used and hiera is just returning the value without trying to decrypt it

**Comment by jas02** [comment]
Hi @TomPoulton, my hiera.yaml:
```
---
:backends:
  - eyaml
  - yaml
:hierarchy:
  - "%{environment}/%{fqdn}"
  - common
:yaml:
  :datadir: '/usr/local/etc/puppet/hiera/'
:eyaml:
  :datadir: '/usr/local/etc/puppet/hiera/'

  :pkcs7_private_key: /etc/puppet/secure/keys/private_key.pkcs7.pem
  :pkcs7_public_key: /etc/puppet/secure/keys/public_key.pkcs7.pem
```

**Comment by jas02** [comment]
@TomPoulton Hi, for example 
```
/usr/local/etc/puppet/hiera/production/support-test.<our_domain>.cz.yaml
```

<our_domain> is of course replaced with correct value.

**Comment by elyscape** [comment]
You'll need to change the extension on the files to `.eyaml`.

**Comment by elyscape** [comment]
A possible alternate solution would be to set `:extension` under `:eyaml` as described [in the documentation](https://github.com/TomPoulton/hiera-eyaml#hiera), but I'm of the opinion that this can make things more confusing and that using `*.eyaml` is generally preferable.

**Comment by TomPoulton** [comment]
Thanks @jas02, as @elyscape said, changing your file extensions to `.eyaml` will mean that your files will be parsed by the eyaml backend and your values will be decrypted.

Yaml formatted files can be parsed by the eyaml backend even if they don't have any encrypted values in them, so I don't actually use the yaml backend at all, I only have the eyaml backend configured. I would recommend doing the same to avoid confusion, just update your `hiera.yaml` file as below and change the extension of all of your hiera data files to `.eyaml`

Alternatively, if you don't want to rename all your files just un-comment the `:extension:` line

```yaml
---
:backends:
  - eyaml
:hierarchy:
  - "%{environment}/%{fqdn}"
  - common
:eyaml:
  # :extension: 'yaml'
  :datadir: '/usr/local/etc/puppet/hiera/'
  :pkcs7_private_key: /etc/puppet/secure/keys/private_key.pkcs7.pem
  :pkcs7_public_key: /etc/puppet/secure/keys/public_key.pkcs7.pem
```

I'll close this issue, but feel free to report back if you're still having problems
