### ISSUE TITLE
Tags missing for versions 2.0.4, 2.0.5, and 2.0.6

### ISSUE THREAD

**Issue by elyscape** [TomPoulton/hiera-eyaml#138]
The missing tags are:
- v2.0.4 for 22e3a46
- v2.0.5 for 7b3eb6b
- v2.0.6 for caf4e01

I recommend creating annotated tags with `git tag -a` and putting each version's changelog in the annotations.  This makes things show up nice on GitHub's releases thing ([for example](https://github.com/elyscape/hiera-eyaml/releases/tag/v2.0.4)).  In the interest of making things simple for you, you can paste the following into the annotations for each version:

`git tag -a v2.0.4 22e3a46`:
```
Version 2.0.4 release

Changes:
- Add change log
- #118 - Some initial support for spaces in filenames (primarily targeted at windows platforms) (@elyscape)
- #114 - Add new config file resolution so that a system wide /etc/eyaml/config.yaml is processed first (@gtmtech)
- #112 - Improve debugging options and colorise output (@gtmtech)
- #102 - Extension of temp files should be yaml to help editors provide syntax highlighting (@ColinHebert)
- #90, #121, #122 - Add preamble in edit mode to make it easier to remember how to edit (@sihil)
- #96, #111, #116 - Various updates to docs
```
`git tag -a v2.0.5 7b3eb6b`:
```
Version 2.0.5 release

Changes:
- #128 - Fix a bug (#117) that caused `eyaml` to break when arguments were supplied in `$EDITOR`
```
`git tag -a v2.0.6 caf4e01`:
```
Version 2.0.6 release

Changes:
- #131 - Fix another EDITOR bug (#130) that could erase command line flags to the specified editor (@elyscape)
```

**Comment by elyscape** [comment]
I have written a tool that automates this and submitted it in #141.

**Comment by elyscape** [comment]
Pinging @sihil, @gtmtech, and @TomPoulton. Any chance of movement on this?

**Comment by TomPoulton** [comment]
I'm on vacation until Tuesday without a laptop so I can look at it then, but @sihil or @gtmtech will probably get there before me
