### ISSUE TITLE
Hiera-eyaml broken with the new version of highline and ruby 1.8

### ISSUE THREAD

**Issue by ColinHebert** [TomPoulton/hiera-eyaml#142]
Since the release of highline 1.7.0, hiera-eyaml breaks with `Notice: hiera(): Cannot load backend eyaml: no such file to load -- io/console`

**Comment by elyscape** [comment]
This is caused by JEG2/highline#129.

**Comment by elyscape** [comment]
@ColinHebert: Highline 1.7.0 has been yanked.  Please remove it with `gem uninstall highline`.  Then install a compatible version of Highline with `gem install highline -v '~> 1.6.19'`.  Then you can install hiera-eyaml.

**Comment by elyscape** [comment]
@TomPoulton: We should probably add something to the documentation indicating that, if you want to install hiera-eyaml on a box that only has Ruby 1.8, you'll need to manually install a compatible version of highline first.

**Comment by hurrycaine** [comment]
No, i believe the right thing to do is to make your dependency
highline ~> 1.6
Or someone could argue that highline should go up a major version ... but >= 1.6.19 would still grab a 2.0 i believe

**Comment by elyscape** [comment]
@hurrycaine That's an option, but it would also mean that hiera-eyaml can't use the newer versions of HighLine, even when on versions of Ruby that are supported.

**Comment by hurrycaine** [comment]
@elyscape Using dependencies with >= actually throws warnings when you build the gem. Its considered best practice (if your dependencies use semantic versioning) to do X ~> 1.0 
For this very use case here.
Once hiera-eyaml no longer wants to support 1.8 ruby then they change it to ~> 1.7

**Comment by elyscape** [comment]
That's fair.  I'll submit a PR soon that changes the dependency.

**Comment by tthayer** [comment]
Thank you!

**Comment by gapotts** [comment]
If you are using puppet to install the following snippet worked for me as a workaround for the time being. Note: this was with puppet 3.7.3.

  package { 'highline':
    ensure   => '1.6.21',
    provider => gem,
  }->
  package { 'hiera-eyaml':
    ensure   => installed,
    provider => gem,
  }

**Comment by TomPoulton** [comment]
This is fixed in v2.0.7, thanks to all

The dependency was changed to `~> 1.6.19` so we'll have to remember to update it once eyaml drops support for 1.8.7. Hopefully there won't be a really cool new feature in highline that we need in the meantime :)

**Comment by elyscape** [comment]
Looks like v2.0.7 [isn't on RubyGems.org yet](https://rubygems.org/gems/hiera-eyaml).

**Comment by elyscape** [comment]
It's up now.  Thanks for all your help and hard work!
