### ISSUE TITLE
Installing highline-1.7.1.gem still results in hiera-eyaml requires highline (~> 1.6.19)

### ISSUE THREAD

**Issue by ltutar** [TomPoulton/hiera-eyaml#147]
I installed the latest available versions of trollop (trollop-2.1.1.gem) and highline (highline-1.7.1). 
After that I tried to install hiera-eyaml-2.0.7.gem, but I got the following error: 
Unable to resolve dependencies: hiera-eyaml requires highline (~> 1.6.19)

I downgraded to highline-1.6.21.gem and then I could install hiera-eyaml-2.0.7.gem

**Comment by elyscape** [comment]
This is expected.  hiera-eyaml does not use any of the features new to HighLine 1.7, which drops compatibility with Ruby 1.8, so the dependency is on the HighLine 1.6 version group.

**Comment by ltutar** [comment]
Thank you. I'll keep using 1.6.x
Have a nice weekend

**Comment by elyscape** [comment]
@ltutar If the problem is resolved, could you close the issue?  Thank you!

**Comment by ltutar** [comment]
I'll close the issue. Thank you for the help.
