### ISSUE TITLE
Notice: hiera(): Cannot load backend eyaml: cannot load such file -- hiera/backend/eyaml_backend

### ISSUE THREAD

**Issue by henryserrano1978** [TomPoulton/hiera-eyaml#148]
I'm running Puppet masterless on Windows 2012R2 and trying to get hiera-eyaml going, but I'm getting the following error:

Notice: hiera(): Cannot load backend eyaml: cannot load such file -- hiera/backend/eyaml_backend

Do you have any documentation for running hiera-eyaml on Windows?

**Comment by elyscape** [comment]
You made sure to install the gem using the Puppet-provided Ruby environment, yes?

**Comment by henryserrano1978** [comment]
That was it! Thanks!

**Comment by elyscape** [comment]
Glad I could help. Would you mind closing the ticket?
