### ISSUE TITLE
What is an "internally json formatted yaml file"?

### ISSUE THREAD

**Issue by r4v5** [TomPoulton/hiera-eyaml#161]
The README.md includes the following harrowing warning:

```
Important Note: The eyaml backend will not parse internally json formatted yaml files, whereas
the regular yaml backend will. You'll need to ensure any existing yaml files using json format
are converted to syntactically correct yaml format.
```

What is an "internally json formatted yaml file", and how would one know if one's existing hieradata contains them?

**Comment by elyscape** [comment]
The YAML spec is designed such that JSON is also valid YAML.  hiera-eyaml doesn't support that.  So, basically, if your .yaml/.eyaml files look like JSON, hiera-eyaml won't be able to parse them.  If they look like regular YAML, you're in the clear.
