### ISSUE TITLE
Doesn't decrypt when using service

### ISSUE THREAD

**Issue by kyledecot** [TomPoulton/hiera-eyaml#175]
When running my puppetserver via `puppet master --no-daemonize` and fetching some keys I get the results that I would expect but when running via `service puppetserver start` and fetching a value with hiera my passwords are not being decrypted.

What would cause this?

My `/etc/puppetlabs/code/hiera.yaml` file looks like:

```---
:backends:
  - eyaml
  - yaml
:eyaml:
  :extension: 'yaml'
  :datadir:
  :pkcs7_private_key: /etc/puppetlabs/secure/keys/private_key.pkcs7.pem
  :pkcs7_public_key:  /etc/puppetlabs/secure/keys/public_key.pkcs7.pem
:yaml:
  :datadir:
:hierarchy:
  - "%{::fqdn}"
  - ruby
  - common
:merge_behavior: deeper
```

**Comment by elyscape** [comment]
Could you please comment on what your problem ended up being?
