### ISSUE TITLE
hiera lookup in a manifest doesn't decrypt

### ISSUE THREAD

**Issue by vikas027** [TomPoulton/hiera-eyaml#177]
I am using the below versions on CentOS 7.1 x86_64 box.
```bash
# /opt/puppetlabs/bin/puppet --version
4.2.2
# /opt/puppetlabs/bin/hiera --version
3.0.3
#
```

Installation through /opt/puppetlabs/bin/puppetserver has below errors.
```bash
# /opt/puppetlabs/bin/puppetserver gem install hiera-eyaml

# find / -iname eyaml  -type f
/opt/puppetlabs/server/data/puppetserver/jruby-gems/bin/eyaml
/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.0.8/bin/eyaml
#
# /opt/puppetlabs/server/data/puppetserver/jruby-gems/bin/eyaml createkeys
/usr/bin/env: jruby: No such file or directory
#
# /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.0.8/bin/eyaml createkeys
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- hiera/backend/eyaml/CLI (LoadError)
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/hiera-eyaml-2.0.8/bin/eyaml:4:in `<main>'
#
```

Installation through /opt/puppetlabs/puppet/bin/gem has no errors, even hiera lookup on a CLI works fine. 
```bash
# hiera -c /etc/puppetlabs/code/hiera.yaml sudo_user_password environment=production
hello123
#
```

But hiera lookup in a manifest fails to decrypt. This echoes the encrypted hash but not the password. The problem remains same, if I install through both the binaries `/opt/puppetlabs/bin/puppetserver` and `/opt/puppetlabs/puppet/bin/gem`
```puppet
$sudo_password = hiera("sudo_user_password")
notify { "$sudo_password" :}
```

Am I missing something ? Thanks for your time on this.

**Comment by vikas027** [comment]
Never mind, I re-did everything again, and it worked. If someone else have a similar issues, follow these commands. Yes, you need to install it twice and use `eyaml` binary of gem installed via puppetserver only. 
```bash
# /opt/puppetlabs/puppet/bin/gem install hiera-eyaml
# /opt/puppetlabs/bin/puppetserver gem install hiera-eyaml
# /opt/puppetlabs/server/data/puppetserver/jruby-gems/bin/eyaml createkeys
```

**Comment by dkoleary** [comment]
Thanks for the solution post.  I was having that exact same issue on puppet server 4.5.  One minor point: the eyaml file to execute is /opt/puppetlabs/puppet/bin/eyaml.

Thanks again.
