### ISSUE TITLE
Compatibility with hiera versions?

### ISSUE THREAD

**Issue by uncleringo** [TomPoulton/hiera-eyaml#178]
I'm desperately trying to get hiera-eyaml working with our puppet master. I've successfully installed the gem (we're running the puppet master via apache). We have hiera version 1.3.4, and hiera-eyaml 2.0.8. Is our hiera too old to support eyaml?

The documentation seems fairly straightforward, and I've managed to encrypt some data, but puppet refuses to play ball. After trying with the hiera CLI it seems to be hiera rather than puppet where the problem lies.

It seems to be ignoring .eyaml files altogether - hiera will successfully look up keys in .yaml files but gives nil to any request for a key in my .eyaml file.

Here's our hiera.yaml (which i've placed in both /etc/hiera.yaml & /etc/puppet/hiera.yaml to no avail):

```yaml
---
:backends:
  - json
  - eyaml
  - yaml
:json:
  :datadir: /etc/puppet/environments/%{::environment}/hieradata
:yaml:                                                                                                                 
  :datadir: /etc/puppet/environments/%{::environment}/hieradata
:eyaml:
  :datadir: /etc/puppet/environments/%{::environment}/hieradata
  :pkcs7_private_key: /etc/puppet/secure/keys/private_key.pkcs7.pem
  :pkcs7_public_key: /etc/puppet/secure/keys/public_key.pkcs7.pem
```

I've tried setting the extension to 'yaml', but the same behaviour happens.

Any suggestions?

**Comment by sihil** [comment]
What version of the puppet master software are you using? In newer releases
you need to install the plugin both into your system ruby and also the
puppetmaster jruby. Look at the install notes in the readme.

**Comment by uncleringo** [comment]
It's puppet version 3.7.4. But it's not running jruby, it's running passenger. If I understand correctly this means it uses the regular system-wide gems. Is that correct?

**Comment by uncleringo** [comment]
The only way I was able to get around this issue in the end was to remove the yaml backend and configure the eyaml extension to be yaml. At least it's a solution
