### ISSUE TITLE
eyamp.pp breaks ACLs on Ext4 file systems

### ISSUE THREAD

**Issue by FayeG** [TomPoulton/hiera-eyaml#204]
The eyamp.pp class defined the private key permissions to be 0600. This value is hard coded.

However when working with a team we use ACL on ext4 using a mask of r--. While this doesn't open up the permissions any more than needed it unfortunately means that via "ls -l" the file looks like it has 0640 permissions when actually is has "-rw-r-----+" and when looking at the ACL 'group' and 'other' are both set to "---", viz:

0 codo:~\# getfacl /etc/puppet/keys/private_key.pkcs7.pem
getfacl: Removing leading '/' from absolute path names
\# file: etc/puppet/keys/private_key.pkcs7.pem
\# owner: puppet
\# group: puppet
user::rw-
user:someuser:r-x              #effective:**r--**
group::---
mask::r--
other::---

0 codo:~# ls -l /etc/puppet/keys/private_key.pkcs7.pem
-rw-r-----+ 1 puppet puppet 1675 Aug  4 14:57 /etc/puppet/keys/private_key.pkcs7.pem
0 codo:~#

Of course  eyamp.pp "fixes" this by setting it back to "0600" and damages the ACL while doing so, viz:

0 codo:~# puppet_run.sh 
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Loading facts
Info: Caching catalog for codo.xxx.xxx
Info: Applying configuration version '[test] 6df1c6c Change Phoenix dnsmasq servers. Both are now link local.'
Notice: /Stage[main]/Hiera::Eyaml/File[/etc/puppet/keys/private_key.pkcs7.pem]/mode: mode changed '0640' to '0600'
Notice: Finished catalog run in 58.87 seconds
0 codo:~# getfacl /etc/puppet/keys/private_key.pkcs7.pem
getfacl: Removing leading '/' from absolute path names
\# file: etc/puppet/keys/private_key.pkcs7.pem
\# owner: puppet
\# group: puppet
user::rw-
user:someuser:r-x              #effective:**---**
group::---
mask::---
other::---

0 codo:~#

Please can the permissions of the private key be made optional so we can pass a value of "0640" into it? 
We already have puppet classes that can handle the ACL part.

**Comment by sihil** [comment]
I believe you want to raise an issue with the `puppet-hiera` project who owns the file you are talking about (for managing `hiera-eyaml` configuration). See https://github.com/voxpupuli/puppet-hiera/blob/master/manifests/eyaml.pp

This project is for the `hiera-eyaml` plugin itself.

Hope you can find a solution quickly.
